baseURL = 'https://doliche.github.io/'
languageCode = 'tr-tr'
title = 'Doliche'
theme = 'PaperMod'

[params]
  [params]
  comments = true
  defaultTheme = 'auto'
  googleAnalytics = ""
  [params.analytics.google]
    SiteVerificationTag = "mol3RVkfmc5AzN_Jaov777_9x39UxeT_KyLgGP5yC8Y"
